import http from 'node:http';import {readFile,writeFile,chmod} from 'node:fs/promises';import {createHandler,readJSON,json} from '../server/worker.mjs';
const port=Number(process.env.PORT||5188),origin=`http://127.0.0.1:${port}`,env={DEEPSEEK_API_KEY:process.env.DEEPSEEK_API_KEY||'',DEEPSEEK_MODEL:process.env.DEEPSEEK_MODEL||'deepseek-flash',LOCAL_SETUP:true};
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{if(req.headers.host!==`127.0.0.1:${port}`){res.writeHead(403);res.end('Unsupported host');return;}
 const url=new URL(req.url,origin),request=new Request(url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:req,duplex:'half'}:{})});let response;
 if(url.pathname==='/setup'||url.pathname==='/setup.js'){const filename=url.pathname==='/setup'?'setup.html':'setup-client.js';response=new Response(await readFile(new URL('../server/'+filename,import.meta.url)),{headers:{'Content-Type':filename.endsWith('.html')?types['.html']:types['.js'],'Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; frame-ancestors 'none'"}});
 }else if(url.pathname==='/api/local-config'){
  if(request.method!=='POST'||request.headers.get('origin')!==origin)response=json({error:'请通过本机配置页面保存。'},403);
  else{const d=await readJSON(request,2000);if(typeof d.apiKey!=='string'||!/^sk-[A-Za-z0-9_-]{12,250}$/.test(d.apiKey))response=json({error:'密钥格式不正确，请完整粘贴 DeepSeek API Key。'},400);
   else{const r=await fetch('https://api.deepseek.com/models',{headers:{Authorization:`Bearer ${d.apiKey}`},signal:AbortSignal.timeout(15000)});if(!r.ok){await r.body?.cancel();response=json({error:r.status===401?'密钥验证未通过，请检查后重试。':'DeepSeek 暂时无法验证，请稍后重试。'},400);}else{await r.body?.cancel();const file=new URL('../.env',import.meta.url);await writeFile(file,`DEEPSEEK_API_KEY=${d.apiKey}\nDEEPSEEK_MODEL=${env.DEEPSEEK_MODEL}\n`,{mode:0o600});await chmod(file,0o600);env.DEEPSEEK_API_KEY=d.apiKey;response=json({configured:true});}}
  }
 }else{const assets={};if(!url.pathname.startsWith('/api/')){const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!name.includes('/')&&!name.includes('..')&&types[name.slice(name.lastIndexOf('.'))]){try{assets[url.pathname==='/'?'/index.html':url.pathname]={body:await readFile(new URL('../public/'+name,import.meta.url),'utf8'),type:types[name.slice(name.lastIndexOf('.'))]};}catch{}}}response=await createHandler({assets})(request,env);}
 res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
 }catch{res.writeHead(500,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({error:'本地服务暂时不可用，请稍后重试。'}));}});server.listen(port,'127.0.0.1',()=>console.log(`Qidian: ${origin}\nLocal setup: ${origin}/setup`));
